title: joeymariano.com
email: joey@joeymariano.com
description: >- # this means to ignore newlines until "baseurl:"
 Homepage of artist, musician, and engineer: Joey Mariano.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://joeymariano.github.io

# Use cards and jobs instead of posts
collections:
 cards:
  output: false # Jobs won't be output as individual pages (optional)
 jobs:
  output: false # Jobs won't be output as individual pages (optional)

# Build settings
plugins:
 - jekyll-feed
 - jekyll-postcss

# Exclude from processing
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list."
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/

postcss:
 cache: false